### ISSUE TITLE
todo part 2

### ISSUE THREAD

**Issue by aadityaaryal** [aadityaaryal/anilist.py#3]
### user related
- [ ] get a user's stats/favs/updates
- [ ] authenticate as a user 
- [ ] update entries 
### fourm related
- [ ] view forum discussion
- [ ] see reviews
